local addon, ns = ...
local O3 = O3

ns.presets = {}

ns.presets.Default = {
	Main = {
		rows = 1,
		columns = 12,
		spacing = 1,
		buttonSize = 36,
		visible = true,
		xOffset = 0,
		yOffset = 4,
		anchor = 'BOTTOM',
		anchorTo = 'BOTTOM',
		anchorParent = 'Screen',
	},
	Second = {
		visible = false,
		rows = 12,
		columns = 1,
		spacing = 1,
		buttonSize = 32,
		xOffset = 0,
		yOffset = 0,
		anchor = 'RIGHT',
		anchorTo = 'RIGHT',
		anchorParent = 'Screen',
	},
	Third = {
		visible = false,
		rows = 12,
		columns = 1,
		spacing = 1,
		buttonSize = 32,
		xOffset = 0,
		yOffset = 0,
		anchor = 'RIGHT',
		anchorTo = 'LEFT',
		anchorParent = 'Second',
	},
	Fourth = {
		visible = false,
		rows = 12,
		columns = 1,
		spacing = 1,
		buttonSize = 32,
		xOffset = 0,
		yOffset = 0,
		anchor = 'RIGHT',
		anchorTo = 'LEFT',
		anchorParent = 'Third',
	},
	Fifth = {
		visible = false,
		rows = 12,
		columns = 1,
		spacing = 1,
		buttonSize = 32,
		xOffset = 0,
		yOffset = 0,
		anchor = 'RIGHT',
		anchorTo = 'LEFT',
		anchorParent = 'Fourth',
	},
	Extra = {
		visible = true,
		buttonSize = 48,
		rows = 1,
		columns = 1,
		spacing = 0,
		xOffset = 0,
		yOffset = 107,
		anchor = 'BOTTOM',
		anchorTo = 'TOP',
		anchorParent = 'Main',
	},
	Pet = {
		rows = 1,
		buttonSize = 32,
		columns = 10,
		spacing = 1,
		visible = true,
		xOffset = 0,
		yOffset = 74,
		anchor = 'BOTTOM',
		anchorTo = 'TOP',
		anchorParent = 'Main',
	}
}

ns.presets['3 Bottom, 2 Side'] = {
	Main = {
		rows = 1,
		columns = 12,
		spacing = 1,
		buttonSize = 36,
		visible = true,
		xOffset = 0,
		yOffset = 4,
		anchor = 'BOTTOM',
		anchorTo = 'BOTTOM',
		anchorParent = 'Screen',
	},
	Second = {
		rows = 1,
		columns = 12,
		spacing = 1,
		buttonSize = 36,
		visible = true,
		xOffset = 0,
		yOffset = 0,
		anchor = 'BOTTOM',
		anchorTo = 'TOP',
		anchorParent = 'Main',
	},
	Third = {
		rows = 1,
		columns = 12,
		spacing = 1,
		buttonSize = 36,
		visible = true,
		xOffset = 0,
		yOffset = 0,
		anchor = 'BOTTOM',
		anchorTo = 'TOP',
		anchorParent = 'Second',
	},
	Fourth = {
		rows = 12,
		columns = 1,
		spacing = 1,
		buttonSize = 32,
		visible = true,
		xOffset = 0,
		yOffset = 0,
		anchor = 'RIGHT',
		anchorTo = 'RIGHT',
		anchorParent = 'Screen',
	},
	Fifth = {
		rows = 12,
		columns = 1,
		spacing = 1,
		buttonSize = 32,
		visible = true,
		xOffset = 0,
		yOffset = 0,
		anchor = 'RIGHT',
		anchorTo = 'LEFT',
		anchorParent = 'Fourth',
	},
	Extra = {
		visible = true,
		buttonSize = 48,
		rows = 1,
		columns = 1,
		spacing = 0,
		xOffset = 0,
		yOffset = 107,
		anchor = 'BOTTOM',
		anchorTo = 'TOP',
		anchorParent = 'Main',
	},
	Pet = {
		rows = 1,
		buttonSize = 32,
		columns = 10,
		spacing = 1,
		visible = true,
		xOffset = 0,
		yOffset = 74,
		anchor = 'BOTTOM',
		anchorTo = 'TOP',
		anchorParent = 'Main',
	}
}

ns.presets['2 Bottom + 2 Split, 1 Side'] = {
	Main = {
		rows = 1,
		columns = 12,
		spacing = 1,
		buttonSize = 32,
		visible = true,
		xOffset = 0,
		yOffset = 4,
		anchor = 'BOTTOM',
		anchorTo = 'BOTTOM',
		anchorParent = 'Screen',
	},
	Second = {
		rows = 1,
		columns = 12,
		spacing = 1,
		buttonSize = 32,
		visible = true,
		xOffset = 0,
		yOffset = 0,
		anchor = 'BOTTOM',
		anchorTo = 'TOP',
		anchorParent = 'Main',
	},
	Third = {
		rows = 2,
		columns = 6,
		spacing = 1,
		buttonSize = 32,
		visible = true,
		xOffset = -10,
		yOffset = 0,
		anchor = 'BOTTOMRIGHT',
		anchorTo = 'BOTTOMLEFT',
		anchorParent = 'Main',
	},
	Fourth = {
		rows = 2,
		columns = 6,
		spacing = 1,
		buttonSize = 32,
		visible = true,
		xOffset = 10,
		yOffset = 0,
		anchor = 'BOTTOMLEFT',
		anchorTo = 'BOTTOMRIGHT',
		anchorParent = 'Main',
	},
	Fifth = {
		rows = 12,
		columns = 1,
		spacing = 1,
		buttonSize = 32,
		visible = true,
		xOffset = 0,
		yOffset = 0,
		anchor = 'RIGHT',
		anchorTo = 'RIGHT',
		anchorParent = 'Screen',
	},
	Extra = {
		visible = true,
		buttonSize = 48,
		rows = 1,
		columns = 1,
		spacing = 0,
		xOffset = 0,
		yOffset = 107,
		anchor = 'BOTTOM',
		anchorTo = 'TOP',
		anchorParent = 'Main',
	},
	Pet = {
		rows = 1,
		buttonSize = 32,
		columns = 10,
		spacing = 1,
		visible = true,
		xOffset = 0,
		yOffset = 74,
		anchor = 'BOTTOM',
		anchorTo = 'TOP',
		anchorParent = 'Main',
	}
}